### ISSUE TITLE
Ljud som saknas i spelet

### ISSUE THREAD

**Issue by salmonslay** [LiterallyFabian/IKIMONO#17]
### Alla ljud som måste läggas in i spelet:
- Musik
  - Default
  - Sleep (det måste finnas en övergång när musiken byts, vi kan **inte** klippa direkt.)
  - Minigame (denna ska **inte** starta om när spelaren startar om minigamet) (denna ska sänkas litegrann när minigamet är över)
- Ljud när Ikimonen äter (finns ett gäng olika loopar som bör spelas, och sist när dessa är **färdiga** swallow.)
- Ljudeffekt från att Ikimonen då och då hickar efter den ätit (kanske typ 0.6 odds per föremål?)
- Ljud när man trycker på en knapp
- Ljud när man försöker trycka på en avstängd knapp 
- Ljud när man köper ett föremål
- Ljud när man byter kategori i en overlay
- Ljud när man stänger en overlay
- Något ljud för när man drar i music/fx sliders - det ska göras tydligt hur hög volymen man byter till är
- Ambience baserat på tid på dygnet
- Ljud från **Ikimonen** när den blir tvättad, med en slumpmässig pitch (Audio/IkimonoSounds/GettingCleaned/IkimonoCleaningNoise.wav)
- Random idle-ljud från Ikimonen då och då (Audio/IkimonoSounds/Happy/HummingN.wav)
- Alternativa idle-ljud från Ikimonen om den är ledsen (Audio/IkimonoSounds/Sad/Squeal1.wav)
- Scratch-ljud från Ikimonen när man klappar den
- Ljud från Ikimonen när den tvättas (detta loopas alldeles för snabbt just nu och behöver en längre cooldown)
- Snarkljud från när Ikimonen sover (detta loopas för snabbt just nu och ljudet överskriver sig själv)
- Minigame game over 
- Minigame coin pick up (ska ha slumpmässig pitch)
- Minigame initial jump 
- Minigame platform jump (ska ha slumpmässig pitch)

Allt ljud måste även använda korrekt audio mixer, och ändras baserat på hur användaren interagerar med denna.

**Comment by Arxhlight** [comment]
- [x] Musik
- [x] Default
- [ ] Sleep (det måste finnas en övergång när musiken byts, vi kan inte klippa direkt.)
- [x] Minigame (denna ska inte starta om när spelaren startar om minigamet) (denna ska sänkas litegrann när minigamet är över)
- [x] Ljud när Ikimonen äter (finns ett gäng olika loopar som bör spelas, och sist när dessa är färdiga swallow.)
- [x] Ljudeffekt från att Ikimonen då och då hickar efter den ätit (kanske typ 0.6 odds per föremål?)
- [x] Ljud när man trycker på en knapp
- [x] Ljud när man försöker trycka på en avstängd knapp
- [x] Ljud när man köper ett föremål
- [x] Ljud när man byter kategori i en overlay
- [x] Ljud när man stänger en overlay
- [x] Något ljud för när man drar i music/fx sliders - det ska göras tydligt hur hög volymen man byter till är
- [x] Ambience baserat på tid på dygnet
- [x] Ljud från Ikimonen när den blir tvättad, med en slumpmässig pitch (Audio/IkimonoSounds/GettingCleaned/IkimonoCleaningNoise.wav)
- [x] Random idle-ljud från Ikimonen då och då (Audio/IkimonoSounds/Happy/HummingN.wav)
- [x] Alternativa idle-ljud från Ikimonen om den är ledsen (Audio/IkimonoSounds/Sad/Squeal1.wav)
- [x] Scratch-ljud från Ikimonen när man klappar den
- [x] Ljud från Ikimonen när den tvättas (detta loopas alldeles för snabbt just nu och behöver en längre cooldown)
- [x] Snarkljud från när Ikimonen sover (detta loopas för snabbt just nu och ljudet överskriver sig själv)
- [x] Minigame game over
- [x] Minigame coin pick up (ska ha slumpmässig pitch)
- [x] Minigame initial jump
- [x] Minigame platform jump (ska ha slumpmässig pitch)

**Comment by Arxhlight** [comment]
[] ljud ambiance för minigame, byte från de andra ambiance ljuden
[] testa nytt ljud för mat

**Comment by salmonslay** [comment]
Avmarkerade ett gäng ljud som inte fanns inlagda, samt;

- Ljud när man byter kategori i en overlay
- Ljud när man stänger en overlay
- Ljud när man trycker på en knapp

Dessa kan inte vara random. Det ger en väldigt dålig användarupplevelse, ljuden måste vara konsekventa. Om du behöver fler ljud kan du assignea någon, men det behöver vara ett eget ljud för varje eget event.

**Comment by Arxhlight** [comment]
Tror inte vi hinner leta upp fler ljud för alla klick, kan ta bort att dom randomizear men det blir bara ett ljud i så fall

**Comment by salmonslay** [comment]
Vi har två att arbeta med, det bör räcka. 

Är Idle-ljuden och snarkljuden verkligen inlagda? Det verkar som att idle bara spelar när man klappar djuret, och snarkljudet bara när en sprite byts ut.

**Comment by Arxhlight** [comment]
Idle ljuden ska bara låta när man klappar Ikimonen, och snarkljudet ska bara låta när man klickar på sov. Så det fungerar som vi tänkte, jag och ellen

**Comment by Arxhlight** [comment]
Utelämnade några av önskningarna, ljud för sliders och att övergångarna i sleep.

**Comment by Arxhlight** [comment]
Utelämnade några av önskningarna, ljud för sliders och att övergångarna i sleep.
