### ISSUE TITLE
Pilarna ändrar inte färg efter minispelet är klart

### ISSUE THREAD

**Issue by salmonslay** [LiterallyFabian/IKIMONO#3]
![image](https://user-images.githubusercontent.com/47401343/168087449-42b77fb8-1fb8-4b5e-85b2-1d24bb0ea921.png)

Bör förmodligen bytas till grön/röd för att hålla det konsekvent med resten av appen. När djuret sover:
![image](https://user-images.githubusercontent.com/47401343/168087555-82d0ee8c-949b-4a54-8559-9553d9939d1c.png)

**Comment by TriKnot** [comment]
Färgerna fixade.
TODO Se till att de visas korrekt efter minigame.

**Comment by TriKnot** [comment]
Fixat och klart.
Ful lösning med många edge cases men det funkar iallafall!
Kan vara värt att lösa om man någonsin jobbar vidare på spelet.
