### ISSUE TITLE
Lägg till en loopande bakgrund i Ikimono Jump

### ISSUE THREAD

**Issue by Arxhlight** [LiterallyFabian/IKIMONO#34]
Vore bra för allt annat i spelet ser bra ut utom just det =) Du pratade om det innan, är det någon asset som behövs kan du ju kolla med danil.

**Comment by salmonslay** [comment]
Ingen aning vad detta ska betyda, men jag antar en repeterande bakgrundsbild istället för den statiska blå-gröna bilden? Isåfall håller jag med.

**Comment by TriKnot** [comment]
Parallax scrolling clouds & stars + sun and moon going across the sky
