### ISSUE TITLE
Bubblor från när djuret tvättas

### ISSUE THREAD

**Issue by salmonslay** [LiterallyFabian/IKIMONO#6]
![image](https://user-images.githubusercontent.com/47401343/168088788-1c41f50e-b703-4322-a4b6-747eadfa03ca.png)

Bör förmodligen visas lite färre, och bilden för dessa måste bytas ut. Jag tilldelar Ellen att rita bilden för bubblan for now, men om någon annan vill ta dem är det bara att köra på. Antar att vi vill ha dem rätt ljusblåa - och kanske lite tjockare linjer? Kom ihåg att de kommer vara små.

**Comment by Arxhlight** [comment]
Bubblan bör ritas i vitt och transparant färg, så det går att ställa lite färgvärlden på den i unity sen. Vitt i kanterna men transparant i mitten. 

Den bubblan jag tog nu är tyvärr svart så den har färg 0, dvs det går inte att ställa någon färgskiftning där =)

**Comment by TriKnot** [comment]
Förstora även partikel objektet så att bubblorna kommer över hela svampen. Just nu kommer de bara fram runt botten av svampen.
